# Generated by Django 6.0.7 on 2026-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_eventsubmission_experiencesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_custom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='experience_custom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_custom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
