# Generated by Django 6.0.7 on 2026-08-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_booking_event_custom_booking_experience_custom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('talent_type', models.CharField(choices=[('MC', 'MC'), ('DJ', 'DJ'), ('HYPEMAN', 'Hypeman'), ('DANCER', 'Dancer')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='talent/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
