# Generated by Django 6.0.7 on 2026-08-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.talent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='talent_custom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
