# Generated by Django 6.0.7 on 2026-08-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_booking_talent_booking_talent_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_custom',
        ),
    ]
