# Generated by Django 6.0.7 on 2026-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_remove_booking_travel_remove_booking_travel_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HOODIE', 'Hoodie'), ('TSHIRT', 'T-Shirt')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colour', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Pink', 'Pink')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collection/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
